// main
export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
export const TOGGLE_MAINPAGE_LOADING = "TOGGLE_MAINPAGE_LOADING";

// setting
export const UPDATE_SELECTED_DIRECTORY = "UPDATE_SELECTED_DIRECTORY"
export const UPDATE_MAX_CONNECTION = "UPDATE_MAX_CONNECTION"

//download
export const UPDATE_DOWNLOAD_LIST = "UPDATE_DOWNLOAD_LIST";